### ISSUE TITLE
rtshellのインストール先について

### ISSUE THREAD

**Issue by orikuma** [start-jsk/rtshell_core#10]
rtshell_core/rtshellにおいてインストール時にいくつか問題があるようです.
1. site-packageとdist-packageの混同
   lib以下にrtshellの類をインストールする際, dist-packageに入るようになっていますが
   openrtm_toolsのrtshell-setup.shのPYTHONPATHの設定と合致していない気がしています.
2. bin以下にrtshellコマンドに必要なスクリプト群が入らない
   make時にrtshellコマンド群がbin以下ではなく直下に配置されてしまいpathが通らなくなっているようです.
3. TimedLongSeqSeqがrtprint出来ない
   hrpsys-base独自と思われるTimedLongSeqSeq型のデータがrtprintからprint出来ないようです. そもそもrtprint内のtypesのリスト内包表記内で見えるmemberにTimedLongSeqSeqが入っていないように思われます.

**Comment by k-okada** [comment]
1) https://github.com/start-jsk/rtshell_core/blob/master/rtshell/catkin.cmake#L10 に書きましたが，dist-packageにインストールするようにしています．catkinだとlib/python2.7/dist-packageが自動でPYTHONPATHに入るためです．rtshell-setup.sh のPYTHONPATHの部分は必要無いですね．

２）binは https://github.com/k-okada/rtshell_core/commit/97f81bc2b3bd1e9ba807421cabfeabce3be02590#commitcomment-5366343　にあるようによくないらしく，lib/openrtm_aist/bin に置きました．ココにあるようにrtshell-seutp.shをかえる必要が有りそうです．

３）https://github.com/gbiggs/rtshell/issues/14 で直るでしょうか？

**Comment by orikuma** [comment]
1, 2についてはrtshell-setup.shの変更が必要な旨了解いたしました.
3については既に試していますが, 前述の通り gbiggs/rtshell#14 該当部分の
inspect.getmembers(m.mod, inspect.isclass)にTimedLongSeqSeqがないことが問題だと思っています.
該当パッチによりTimedDoubleSeqをはじめとするopenrtmのデータがprint出来ることは確認済みです.
