### ISSUE TITLE
release

### ISSUE THREAD

**Issue by k-okada** [start-jsk/rtshell_core#32]
MEMO: #31 is worth to include in release version

**Comment by k-okada** [comment]
once rtshell_coreis  released, merge https://github.com/start-jsk/rtmros_common/pull/404

**Comment by k-okada** [comment]
@130s I understand you do not like to release, but before I forget about this, #31 it allow users to use rtprint which is openrtm version of `rostopic echo`.

**Comment by 130s** [comment]
Current version is `3.0.0-3` on G and H. Will next version be 3.0.0-4 or 3.0.1 or else?

**Comment by k-okada** [comment]
It may 3.0.0-4.  Sorry.
I asked rtshell to add new release number -> https://github.com/gbiggs/rtshell/issues/17

**Comment by k-okada** [comment]
Let's wait one-two days if @gbiggs accept our proposal

**Comment by k-okada** [comment]
3.0.1 is released ! we can change https://github.com/start-jsk/rtshell_core/blob/master/rtshell/Makefile.rtshell#L6, to download newer version.

**Comment by 130s** [comment]
Looks like it's done thank you! https://github.com/ros/rosdistro/pull/3914 https://github.com/ros/rosdistro/pull/3910?utm_campaign=website&utm_source=sendgrid.com&utm_medium=email
