### ISSUE TITLE
No more meta pkg since Indigo?

### ISSUE THREAD

**Issue by 130s** [start-jsk/rtshell_core#43]
I don't follow the reason why each package is separately released into Indigo, but it looks like it is not recommended according to the ROS maintainer. https://github.com/ros/rosdistro/pull/7125

**Comment by k-okada** [comment]
we no longer use rospackage for aist programs, directory releaed from
tork/~*repoisitory (https://github.com/tork-a/rtshell-release/tree/master)
 as suggested http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty

## 

◉ Kei Okada

**Comment by k-okada** [comment]
cf:
https://github.com/start-jsk/rtmros_common/issues/595#issuecomment-73397941

## 

◉ Kei Okada

**Comment by 130s** [comment]
> we no longer use rospackage for aist programs, directory releaed from tork/~*repoisitory

I see. But do we need to release each package in `rtshell_core` 1 by 1? If so, we need to split release repository as suggested in https://github.com/ros/rosdistro/pull/7125

**Comment by k-okada** [comment]
they are already split
https://github.com/tork-a/rtshell-release
https://github.com/tork-a/rtsprofile-release
https://github.com/tork-a/rtctree-release

## 

◉ Kei Okada

**Comment by 130s** [comment]
Got it!
